---
- name: Install and Configure Nginx
  hosts: mywebservers
  become: yes
  tasks:
    - name: Install Nginx on Debian-based systems
      ansible.builtin.package:
        name: nginx
        state: present
      notify: restart nginx

    - name: Install Nginx on Red Hat-based systems
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: restart nginx

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
