---
- name: Ensure the directory exists
  file:
    path: /tmp/test
    state: directory
    mode: '0755'

- name: Create an empty file
  file:
    path: /tmp/test/created_file.txt
    state: touch
    mode: '0644'

- name: Create a file with specific content
  copy:
    dest: /tmp/test/created_file_with_content.txt
    content: |
      This file was created by Ansible.
      It contains some example content.
    mode: '0644'
