---
- name: Install and Start httpd Server
  hosts: all
  become: yes
  tasks:
    - name: Install the httpd package
      dnf:
        name: httpd
        state: present


    - name: Ensure the httpd service is stopped
      service:
        name: httpd
        state: stopped
        enabled: yes
      # The `enabled` parameter ensures the service is enabled on boot
