---
- name: Download and Configure Apache Tomcat 10
  hosts: mywebservers
  tasks:
    - name: Create a directory to store Tomcat
      file:
        path: /opt/tomcat
        state: directory

    - name: Download Apache Tomcat 10 tar.gz
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.0.15/bin/apache-tomcat-10.0.15.tar.gz"
        dest: /opt/tomcat/apache-tomcat-10.0.15.tar.gz
        mode: '0644'
        timeout: 120

    - name: Extract Apache Tomcat 10
      unarchive:
        src: /opt/tomcat/apache-tomcat-10.0.15.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        creates: /opt/tomcat/apache-tomcat-10.0.15

    - name: Remove the downloaded tar.gz file
      file:
        path: /opt/tomcat/apache-tomcat-10.0.15.tar.gz
        state: absent
