# File: download_tomcat_tasks.yml

- name: Create directory for Tomcat installation
  ansible.builtin.win_shell: mkdir C:\opt\tomcat

- name: Download Apache Tomcat 9.0.71
  ansible.builtin.win_get_url:
    url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71-windows-x64.zip"
    dest: C:\opt\tomcat\apache-tomcat-9.0.71.zip

- name: Extract Apache Tomcat 9.0.71
  ansible.builtin.win_unzip:
    src: C:\opt\tomcat\apache-tomcat-9.0.71.zip
    dest: C:\opt\tomcat
    creates: C:\opt\tomcat\apache-tomcat-9.0.71
