---
- name: Stop Apache HTTP Server on Ubuntu and Red Hat-based Systems
  hosts: mywebservers
  become: yes
  tasks:
    - name: Gather system facts
      setup:

    - name: Stop apache2 on Debian-based systems
      service:
        name: "{mywebpackonubuntu}"
        state: stopped
      when: ansible_facts['os_family'] == "Debian"

    - name: Stop httpd on Red Hat-based systems
      service:
        name: "{mywebpack0nredhat}"
        state: stopped
      when: ansible_facts['os_family'] == "RedHat"
