---
- name: Gather facts and start Apache2
  hosts: all
  become: yes
  tasks:
    - name: Start Apache2 on Debian-based systems
      service:
        name: apache2
        state: started
      when: ansible_facts['os_family'] == "Debian"
