---
- name: Stop Apache HTTP Server on Ubuntu and Red Hat-based Systems
  hosts: all
  become: yes
  tasks:
    - name: Gather system facts
      setup:

    - name: Stop apache2 on Debian-based systems
      service:
        name: apache2
        state: stopped
      when: ansible_facts['os_family'] == "Debian"

    - name: Stop httpd on Red Hat-based systems
      service:
        name: httpd
        state: stopped
      when: ansible_facts['os_family'] == "RedHat"
