---
- hosts: 10.0.2.69
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myfirsttaskresults
  - name: i want to display first task results using debug
    debug:
       msg: "{{myfirsttaskresults}}"
