---
- hosts: 10.0.2.69
  become: yes
  tasks:
    - name: Execute a direct Linux command
      command: hostname -f
      register: myfirsttaskresults

    - name: Display first task results using debug
      debug:
        msg: "{{myfirsttaskresults}}"  # Fix to display the output of the command

    - name: Install git
      apt:
        name: git
        state: present
      when: myfirsttaskresults.stderr == ""  # Condition for installing git

    - name: Install tree
      apt:
        name: tree
        state: present
      when: myfirsttaskresults.stderr != ""  # Condition for installing tree
