---
- hosts: mywebservers
  become: yes
  tasks:
  - name: include task yaml
   # include_tasks: myfile.yml
   # include_tasks: create_file_playbook.yml
    include_tasks: copy_file_from_master_to_node.yml