---
- hosts: 10.0.3.238
  become: yes
  tasks:
    - name: Install git
      dnf:
        name: git
        state: present
      tags:
        - mygit

    - name: Install tree
      dnf:
        name: tree
        state: present
      tags:
        - tree

    - name: Install wget
      dnf:
        name: wget
        state: present
      tags:
        - wget
