---
- name: Uninstall apache2
  hosts: 10.0.2.69
  become: yes
  tasks:
  - name: Install Apache2 on Debian-based systems
    apt:
     name: "{{mywebpackonubuntu}}"
     state: absent
    when: ansible_facts['os_family'] == "Debian"
