---
- name: Create tomcat user
  user:
    name: tomcat
    home: /opt/tomcat
    shell: /bin/false
    create_home: yes

- name: Download Tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /tmp/apache-tomcat-10.0.20.tar.gz

- name: Extract Tomcat
  unarchive:
    src: /tmp/apache-tomcat-10.0.20.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Set ownership and permissions
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Set executable permissions for Tomcat scripts
  file:
    path: /opt/tomcat/bin
    mode: u+x
    recurse: yes
